name: Trigger knmt-website Update

on:
  push:
    branches:
      - main

jobs:
  trigger-repo-a:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger knmt-website's workflow via repository_dispatch
      run: |
        curl -X POST https://api.github.com/repos/ronia-jakim/knmt-website/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.REPO_A_PAT }}" \
          -d '{"event_type":"update-submodule"}'
